# 配置protoc生成规则
version: v1
managed:
  enabled: false
plugins:
  # generate openapi v2 json doc
#  - name: openapiv2
#    out: gen/api/go
#    opt:
#      - json_names_for_fields=true
#      - logtostderr=true
  # generate openapi v2 yaml doc
  - name: openapi
    out: gen/api/go/admin/service/v1
    opt:
      - naming=json
      - paths=source_relative
