on: [ push, pull_request ]
name: build
jobs:

  test:
    strategy:
      matrix:
        go-version: [ 1.19.x ]
        os: [ ubuntu-latest ]
        targetplatform: [ x64 ]

    runs-on: ${{ matrix.os }}

    steps:

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install Buf
        uses: bufbuild/buf-setup-action@v1

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install protoc plugins
        shell: bash
        run: ./.github/scripts/install_protoc_plugins.sh

      - name: Generate API
        shell: bash
        run: ./.github/scripts/generate_api.sh

      - name: Get dependencies
        run: |
          env GO111MODULE=on go vet ./blog-backend/...

      - name: Build
        shell: bash
        run: ./.github/scripts/build_server.sh

      - name: Test
        run: env GO111MODULE=on go test -v -timeout 30m -race ./blog-backend/... -coverprofile=coverage.txt -covermode=atomic

      - name: Codecov
        uses: codecov/codecov-action@v3
        with:
          file: coverage.txt
          flags: unittests
          name: codecov-umbrella
